AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket creation and replication

Parameters:
  PrimaryBucket:
    Type: String
    Default: "photo-blog-app-primary-bucket"
    Description: Primary bucket
  BackupBucket:
    Type: String
    Default: "photo-blog-app-backup-bucket"
    Description: Backup bucket
  PrimaryStagingBucket:
    Type: String
    Default: "photo-blog-app-primary-staging-bucket"
    Description: Primary staging bucket
  BackupStagingBucket:
    Type: String
    Default: "photo-blog-app-backup-staging-bucket"
    Description: Backup staging bucket
  PrimaryRegion:
    Type: String
    Default: "eu-central-1"
    Description: Primary region for disaster recovery
  BackupRegion:
    Type: String
    Default: "eu-west-1"
    Description: Backup region for disaster recovery

Conditions:
  IsPrimaryRegion: !Equals [!Ref AWS::Region, !Ref PrimaryRegion]
  IsBackupRegion: !Equals [!Ref AWS::Region, !Ref BackupRegion]

Resources:
  # Primary S3 bucket (created in Primary Region)
  PrimaryBucketResource:
    Type: AWS::S3::Bucket
    Condition: IsPrimaryRegion
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref PrimaryBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt S3ReplicationRole.Arn
        Rules:
          - Status: Enabled
            Priority: 1
            Filter:
              Prefix: ""
            DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: !Sub arn:aws:s3:::${BackupBucket}

  # Backup bucket (created in Backup Region)
  BackupPrimaryBucket:
    Type: AWS::S3::Bucket
    Condition: IsBackupRegion
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BackupBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  # Primary Staging S3 bucket (created in Primary Region)
  PrimaryStagingBucketResource:
    Type: AWS::S3::Bucket
    Condition: IsPrimaryRegion
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref PrimaryStagingBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Backup Staging S3 bucket (created in Backup Region)
  BackupStagingBucketResource:
    Type: AWS::S3::Bucket
    Condition: IsBackupRegion
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BackupStagingBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Primary Staging bucket policy (only applies in Primary Region)
  PrimaryStagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsPrimaryRegion
    Properties:
      Bucket: !Ref PrimaryStagingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${PrimaryStagingBucket}/*'

  # Backup Staging bucket policy (only applies in Backup Region)
  BackupStagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsBackupRegion
    Properties:
      Bucket: !Ref BackupStagingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${BackupStagingBucket}/*'

  # Primary bucket policy (applies only in Primary Region)
  PrimaryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsPrimaryRegion
    Properties:
      Bucket: !Ref PrimaryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${PrimaryBucket}/*'

  # Backup bucket policy (applies only in Backup Region)
  BackupPrimaryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsBackupRegion
    Properties:
      Bucket: !Ref BackupBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${BackupBucket}/*'

  # S3 replication role (created in Primary Region)
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Condition: IsPrimaryRegion
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${PrimaryBucket}"
                  - !Sub "arn:aws:s3:::${PrimaryBucket}/*"
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                  - s3:ObjectOwnerOverrideToBucketOwner
                Resource:
                  - !Sub "arn:aws:s3:::${BackupBucket}/*"
