AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::photo-blog-app
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Parameters:
  FrontendDevHost:
    Type: String
    Default: "http://localhost:4200"
    Description: The localhost of my frontend
  FrontendProdHost:
    Type: String
    Default: "http://localhost:4200"
    Description: The localhost of my frontend

Resources:
  ## Lambda function for API-GATEWAY
  PhotoBlogAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource:
              - !GetAtt PrimaryBucket.Arn
              - !GetAtt StagingBucket.Arn
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt ImageProcessingLambda.Arn
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          S3_BUCKET_PRIMARY: !Ref PrimaryBucket
          S3_BUCKET_STAGING: !Ref StagingBucket
          DYNAMODB_TABLE: !Ref Table
          IMAGE_PROCESSING_LAMBDA: !Ref ImageProcessingLambda

  # Lambda Function for SQS Notification Processing
  ImageProcessingLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ImageProcessingLambda
      Handler: org.example.ImageProcessingLambda::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt PrimaryBucket.Arn
              - !GetAtt StagingBucket.Arn
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource:
                - !GetAtt StepFunctionStateMachine.Arn
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
            Resource: !GetAtt Table.Arn
      Environment:
        Variables:
          S3_BUCKET_PRIMARY: !Ref PrimaryBucket
#          S3_BUCKET_STAGING: !Ref StagingBucket
          DYNAMODB_TABLE: !Ref Table
          STEP_FUNCTION_ARN: !Ref StepFunctionStateMachine

  # Lambda Function for SES Notification Processing
  NotifyUserLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-NotifyUserLambda
      Handler: org.example.NotifyUserLambda::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole

  StagingBucket:
    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}-staging-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PrimaryBucket:
    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}-primary-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-UserPoolClient
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - aws.cognito.signin.user.admin
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - !Ref FrontendDevHost
        - !Ref FrontendProdHost
      UserPoolId: !Ref UserPool
      RefreshTokenValidity: 30
      AccessTokenValidity: 6
      IdTokenValidity: 6
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  # Cognito User Pool Domain
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::StackName}-domain
      UserPoolId: !Ref UserPool

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Table
      AttributeDefinitions:
        - AttributeName: photoId
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
      KeySchema:
        - AttributeName: photoId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OwnerIndex
          KeySchema:
            - AttributeName: owner
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  StepFunctionStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${AWS::StackName}-StepFunctionStateMachine
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: !Sub |
        {
          "StartAt": "DetermineWorkflow",
          "States": {
            "DetermineWorkflow": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.workflowType",
                  "StringEquals": "image-processing-retry",
                  "Next": "CheckRetryAttempt"
                }
              ],
              "Default": "FailState"
            },
            "CheckRetryAttempt": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.retryAttempt",
                  "NumericLessThan": 3,
                  "Next": "WaitBeforeRetry"
                }
              ],
              "Default": "FailState"
            },
            "WaitBeforeRetry": {
              "Type": "Wait",
              "Seconds": 300,
              "Next": "ImageProcessing"
            },
            "ImageProcessing": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-ImageProcessingLambda",
              "Parameters": {
                "bucketName.$": "$.bucketName",
                "objectKey.$": "$.objectKey",
                "email.$": "$.email",
                "fullName.$": "$.fullName",
                "retryAttempt.$": "$.retryAttempt"
              },
              "Next": "SuccessState"
            },
            "SuccessState": {
              "Type": "Succeed"
            },
            "FailState": {
              "Type": "Fail",
              "Error": "ProcessingFailed",
              "Cause": "Image processing failed after retries."
            }
          }
        }

# BUCKET POLICIES

  # Staging bucket policy
  StagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StagingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${StagingBucket}/*'

  # Primary bucket policy
  PrimaryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PrimaryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${PrimaryBucket}/*'

  # IAM ROLES
  # Step Functions Role
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-ImageProcessingLambda


Outputs:
  PhotoBlogAppApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: PhotoBlogAppApi

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  UserPoolDomainURL:
    Description: Cognito User Pool Domain Hosted UI URL
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com

  CognitoLoginURL:
    Description: Cognito User Pool Application Client Hosted Login UI URL
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=code&redirect_uri=${FrontendProdHost}'

  PrimaryS3Bucket:
    Description: Primary s3 bucket
    Value: !Ref PrimaryBucket

  StagingS3Bucket:
    Description: Staging s3 bucket
    Value: !Ref StagingBucket