name: Deploy Photo Blog Application

on:
  pull_request:
    types: [closed]
    branches:
      - test
      - prod

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIMARY_REGION: ${{ secrets.AWS_REGION }}
  BACKUP_REGION: ${{ secrets.BACKUP_REGION }}

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Build with SAM
        run: sam build

      - name: Upload SAM Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-build-artifacts
          path: .aws-sam/build

  deploy:
    name: Deploy to AWS (Test/Prod)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download SAM Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sam-build-artifacts
          path: .aws-sam/build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Primary Region
        run: |
          echo "Deploying to Primary Region: $PRIMARY_REGION"
          PARAM_OVERRIDES=""
          if [ -n "$PRIMARY_REGION" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES PrimaryRegion=$PRIMARY_REGION"
          fi
          
          if [ -n "$BACKUP_REGION" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES BackupRegion=$BACKUP_REGION"
          fi
          
          if [ -n "$FRONT_END_URI" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES FrontendProdHost=$FRONT_END_URI"
          fi
          
          if [ -n "$PARAM_OVERRIDES" ]; then
            PARAM_OVERRIDES="--parameter-overrides $PARAM_OVERRIDES"
          fi
          
          sam deploy --no-confirm-changeset \
          --stack-name photo-blog-app-${{ github.ref == 'refs/heads/test' && 'test' || 'prod' }} \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region $PRIMARY_REGION \
          $PARAM_OVERRIDES

      - name: Deploy to Backup Region
        run: |
          echo "Deploying to Backup Region: $BACKUP_REGION"
          PARAM_OVERRIDES=""
          if [ -n "$PRIMARY_REGION" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES PrimaryRegion=$PRIMARY_REGION"
          fi
          
          if [ -n "$BACKUP_REGION" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES BackupRegion=$BACKUP_REGION"
          fi
          
          if [ -n "$FRONT_END_URI" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES FrontendProdHost=$FRONT_END_URI"
          fi
          
          if [ -n "$PARAM_OVERRIDES" ]; then
            PARAM_OVERRIDES="--parameter-overrides $PARAM_OVERRIDES"
          fi
          sam deploy --no-confirm-changeset \
          --stack-name photo-blog-app-${{ github.ref == 'refs/heads/test' && 'test' || 'prod' }} \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region $BACKUP_REGION \
          $PARAM_OVERRIDES
